version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306



#### ENTRANDO NO BANCO
# docker compose exec mysql bash
#  mysql -u root -p goexpert
# CREATE TABLE PRODUCTS (ID VARCHAR(255), NAME VARCHAR(80), PRICE DECIMAL(10,2), PRIMARY KEY(ID));